openapi: 3.0.0
info:
  title: Tenants
  version: '1.0'
  description: To onboard properly into the Fiserv Developer Portal as a tenant each product must support these APIs so that we can retrieve product specific API specifications and documentation.
  contact:
    name: help
    email: help@dev.fiserv.com
    url: 'http://dev.fiserv.com/help'
  termsOfService: 'http://dev.fiserv.com/tos'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{product}':
    parameters:
      - schema:
          type: string
        name: product
        in: path
        required: true
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  title:
                    type: string
                    minLength: 1
                  logoURL:
                    type: string
                    minLength: 1
                  description:
                    type: string
                    minLength: 1
                  categories:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - categoryId
                        - name
                        - value
                      properties:
                        categoryId:
                          type: number
                        name:
                          type: string
                          minLength: 1
                        value:
                          type: string
                          minLength: 1
                        subcategories:
                          type: array
                          items:
                            required: []
                            properties: {}
                  tags:
                    type: array
                    items:
                      required: []
                      properties: {}
                  solution:
                    type: string
                    minLength: 1
                  products:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - id
                        - title
                        - name
                        - featured
                        - logoURL
                        - description
                        - apiSpecification
                        - format
                        - documentation
                        - layout
                      properties:
                        id:
                          type: string
                          minLength: 1
                        title:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                        categories:
                          type: array
                          items:
                            required: []
                            properties: {}
                        tags:
                          type: array
                          items:
                            required: []
                            properties: {}
                        featured:
                          type: boolean
                        logoURL:
                          type: string
                          minLength: 1
                        description:
                          type: string
                          minLength: 1
                        apiSpecification:
                          type: string
                          minLength: 1
                        format:
                          type: string
                          minLength: 1
                        documentation:
                          type: string
                          minLength: 1
                        layout:
                          type: string
                required:
                  - title
                  - logoURL
                  - description
                  - categories
                  - tags
                  - solution
                  - products
              examples:
                Get product metadata:
                  value:
                    title: Carat
                    logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
                    description: |-
                      Our powerful omnichannel commerce solutions help companies reach untapped markets and expand globally without being limited by borders, currencies or old ways of thinking.
                            Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce.
                            Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce. Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce.
                    categories:
                      - categoryId: 100
                        name: RETAIL
                        value: Retail
                        subcategories: []
                      - categoryId: 101
                        name: RESTAURANT
                        value: Restaurant
                        subcategories: []
                      - categoryId: 102
                        name: MOTO
                        value: Moto (Mail Order Telephone Order)
                        subcategories: []
                      - categoryId: 103
                        name: ECOMMERCE
                        value: Ecommerce
                        subcategories: []
                      - categoryId: 104
                        name: LODGING
                        value: Lodging
                        subcategories: []
                      - categoryId: 105
                        name: CAR_RENTAL
                        description: Car Rental
                        subcategories: []
                      - categoryId: 106
                        name: PETROLEUM
                        value: Petro
                        subcategories: []
                      - categoryId: 107
                        name: QSR
                        value: QSR (Quick Service Restaurant)
                        subcategories: []
                      - categoryId: 117
                        name: CASH_ADVANCE
                        description: Cash Advance
                        subcategories: []
                    tags:
                      - ecommerce
                      - payments
                      - Enterprise
                      - Reporting
                    solution: Payments
                    products:
                      - id: '1'
                        categories:
                          - ECOMMERCE
                          - LODGING
                        tags:
                          - ecommerce
                          - payments
                          - Enterprise
                        featured: true
                        name: CommerceHub
                        title: Commerce Hub
                        logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
                        description: Authoritatively disseminate prospective leadership via opportunities economically sound.
                        apiSpecification: /v1/products/commercehub/swagger
                        layout: /v1/products/commercehub/layouts/productPage
                        documentation: /v1/products/commercehub/docs
                      - id: '2'
                        name: CLX
                        title: ClientLineX
                        categories:
                          - RETAIL
                          - QSR
                        tags:
                          - Enterprise
                          - Reporting
                        featured: true
                        logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
                        description: Authoritatively disseminate prospective leadership via opportunities economically sound.
                        apiSpecification: /v1/products/CLX/swagger
                        documentation: /v1/products/CLX/docs
                        layout: ''
                      - id: '3'
                        title: ACH
                        name: ACH Invoices
                        categories:
                          - ECOMMERCE
                          - RETAIL
                          - MOTO
                        tags:
                          - ecommerce
                          - payments
                          - Enterprise
                        featured: false
                        logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
                        description: Authoritatively disseminate prospective leadership via opportunities economically sound.
                        apiSpecification: /v1/product/ACH/swagger
                        format: yaml
                        documentation: /v1/products/ACH/docs
                        layout: ''
          headers: {}
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
  /apis:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
    parameters: []
  /docs:
    post:
      summary: ''
      operationId: post-docs
      responses:
        '200':
          description: OK
  /layouts:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-layouts
  /live:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-live
  /ready:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-ready
  /about:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      operationId: get-about
components:
  schemas:
    User:
      description: ''
      type: object
      properties:
        title:
          type: string
          minLength: 1
        logoURL:
          type: string
          minLength: 1
        description:
          type: string
          minLength: 1
        categories:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
              - categoryId
              - name
              - value
            properties:
              categoryId:
                type: number
              name:
                type: string
                minLength: 1
              value:
                type: string
                minLength: 1
              subcategories:
                type: array
                items:
                  required: []
                  properties: {}
        tags:
          type: array
          items:
            required: []
            properties: {}
        solution:
          type: string
          minLength: 1
        products:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
              - id
              - title
              - name
              - featured
              - logoURL
              - description
              - apiSpecification
              - format
              - documentation
              - layout
            properties:
              id:
                type: string
                minLength: 1
              title:
                type: string
                minLength: 1
              name:
                type: string
                minLength: 1
              categories:
                type: array
                items:
                  required: []
                  properties: {}
              tags:
                type: array
                items:
                  required: []
                  properties: {}
              featured:
                type: boolean
              logoURL:
                type: string
                minLength: 1
              description:
                type: string
                minLength: 1
              apiSpecification:
                type: string
                minLength: 1
              format:
                type: string
                minLength: 1
              documentation:
                type: string
                minLength: 1
              layout:
                type: string
      required:
        - title
        - logoURL
        - description
        - categories
        - tags
        - solution
        - products
      x-examples:
        Commerce Hub:
          title: Carat
          logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
          description: |-
            Our powerful omnichannel commerce solutions help companies reach untapped markets and expand globally without being limited by borders, currencies or old ways of thinking.
                  Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce.
                  Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce. Carat's single-source commerce engine makes the process seamless, effortless, and secure. We've unified our suite of solutions into a powerful tech ecosystem so you can create commerce.
          categories:
            - categoryId: 100
              name: RETAIL
              value: Retail
              subcategories: []
            - categoryId: 101
              name: RESTAURANT
              value: Restaurant
              subcategories: []
            - categoryId: 102
              name: MOTO
              value: Moto (Mail Order Telephone Order)
              subcategories: []
            - categoryId: 103
              name: ECOMMERCE
              value: Ecommerce
              subcategories: []
            - categoryId: 104
              name: LODGING
              value: Lodging
              subcategories: []
            - categoryId: 105
              name: CAR_RENTAL
              description: Car Rental
              subcategories: []
            - categoryId: 106
              name: PETROLEUM
              value: Petro
              subcategories: []
            - categoryId: 107
              name: QSR
              value: QSR (Quick Service Restaurant)
              subcategories: []
            - categoryId: 117
              name: CASH_ADVANCE
              description: Cash Advance
              subcategories: []
          tags:
            - ecommerce
            - payments
            - Enterprise
            - Reporting
          solution: Payments
          products:
            - id: '1'
              categories:
                - ECOMMERCE
                - LODGING
              tags:
                - ecommerce
                - payments
                - Enterprise
              featured: true
              name: CommerceHub
              title: Commerce Hub
              logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
              description: Authoritatively disseminate prospective leadership via opportunities economically sound.
              apiSpecification: /v1/products/commercehub/swagger
              layout: /v1/products/commercehub/layouts/productPage
              documentation: /v1/products/commercehub/docs
            - id: '2'
              name: CLX
              title: ClientLineX
              categories:
                - RETAIL
                - QSR
              tags:
                - Enterprise
                - Reporting
              featured: true
              logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
              description: Authoritatively disseminate prospective leadership via opportunities economically sound.
              apiSpecification: /v1/products/CLX/swagger
              documentation: /v1/products/CLX/docs
              layout: ''
            - id: '3'
              title: ACH
              name: ACH Invoices
              categories:
                - ECOMMERCE
                - RETAIL
                - MOTO
              tags:
                - ecommerce
                - payments
                - Enterprise
              featured: false
              logoURL: 'https://raw.githubusercontent.com/tomeck/transactionenrichmentstoplight/main/docs/carat_logo.png'
              description: Authoritatively disseminate prospective leadership via opportunities economically sound.
              apiSpecification: /v1/product/ACH/swagger
              format: yaml
              documentation: /v1/products/ACH/docs
              layout: ''
